name: "CodeQL for C# on Windows"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 18 * * 1'

jobs:
  analyze:
    name: Analyze C#
    runs-on: windows-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Find solution file
      id: find-sln
      shell: pwsh
      run: |
        $slnFile = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
        if (-not $slnFile) {
          Write-Error "No .sln file found in the repository"
          exit 1
        }
        Write-Output "SLN_PATH=$($slnFile.FullName)" >> $env:GITHUB_ENV
        Write-Output "PROJECT_DIR=$($slnFile.DirectoryName)" >> $env:GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore "${{ env.SLN_PATH }}"
      working-directory: "${{ env.PROJECT_DIR }}"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'
        build-mode: 'autobuild'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
